# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Echobin < Formula
  desc "Yet another Golang port of httpbin, powered by echo framework."
  homepage "https://github.com/masakichi/echobin"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/masakichi/echobin/releases/download/0.9.2/echobin_0.9.2_Darwin_arm64.tar.gz"
      sha256 "fe4217043a8e09ee0c8265bc5b1833aabfeddd06d5505babe0eb7f0f1f6be5fb"

      def install
        bin.install "echobin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masakichi/echobin/releases/download/0.9.2/echobin_0.9.2_Darwin_x86_64.tar.gz"
      sha256 "2c142da534af61223d9f8fef81ae4508739431b1df1d8c94c6e2cf5aee334664"

      def install
        bin.install "echobin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masakichi/echobin/releases/download/0.9.2/echobin_0.9.2_Linux_arm64.tar.gz"
      sha256 "09c567b3e3c932af6f5720eba3575cabb3a8782bfe2126a1fa6c581b621c4ed6"

      def install
        bin.install "echobin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/masakichi/echobin/releases/download/0.9.2/echobin_0.9.2_Linux_x86_64.tar.gz"
      sha256 "5c78a07f88e0406da21f4b395f01e0a3a58026526ade443be10af19a14b822fc"

      def install
        bin.install "echobin"
      end
    end
  end
end
