# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JflintGo < Formula
  desc "jflint-go helps to lint a Declarative Jenkinsfile."
  homepage "https://github.com/masakichi/jflint-go"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masakichi/jflint-go/releases/download/v1.0.0/jflint-go_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "9db80cdb9e9fb90a80e13ac03b7d3201c7b6336a2111745079b8664ca7e79780"
    end
    if Hardware::CPU.arm?
      url "https://github.com/masakichi/jflint-go/releases/download/v1.0.0/jflint-go_1.0.0_Darwin_arm64.tar.gz"
      sha256 "d8a2a382ec9d8ec266b44fff7a166d552634a4a8cbce678a1beead3d7c31786f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/masakichi/jflint-go/releases/download/v1.0.0/jflint-go_1.0.0_Linux_x86_64.tar.gz"
      sha256 "b7f5a966d212ae94f6708a303facdc2907ac3ca2333e12fb95fbdd388976360b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masakichi/jflint-go/releases/download/v1.0.0/jflint-go_1.0.0_Linux_arm64.tar.gz"
      sha256 "7bb69765dbcd3384676755fc7a8b4b0fe411ef48968d5da662fe03d50b15dd92"
    end
  end

  def install
    bin.install "jflint-go"
  end
end
