# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tango < Formula
  desc "Tango(単語) is a local command-line Japanese dictionary tool using yomichan's dictionary files."
  homepage "https://github.com/masakichi/tango"
  version "1.1.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/masakichi/tango/releases/download/v1.1.0/tango_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "95a2c28badbb9ae7e90e527b473ccb19b021d1e841ac2dfe84ca8cbabbedb6d8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/masakichi/tango/releases/download/v1.1.0/tango_1.1.0_Darwin_arm64.tar.gz"
      sha256 "02f201e4ae20f6c04e8d7051ea64bfb74447ae83a1d8d62192196a793a0597e1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/masakichi/tango/releases/download/v1.1.0/tango_1.1.0_Linux_x86_64.tar.gz"
      sha256 "a9b305359d45c30f83a7411e988e8fa1dce337f389dfa652ec78067be84ca08b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/masakichi/tango/releases/download/v1.1.0/tango_1.1.0_Linux_arm64.tar.gz"
      sha256 "8427fd5a4eed89840cc1cfaca70595a9ff199049fd82bf1981411f9cb81c5544"
    end
  end

  def install
    bin.install "tango"
  end
end
